# Первое задание.
Реализуйте XOR с помощью 3 нейронов.

In [3]:
import torch 
class Neuron(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.fc = torch.nn.Linear(2, 1)

  def forward(self, x):
    return torch.heaviside(self.fc(x), torch.tensor([0.0]))


In [32]:
neuron1 = Neuron()
neuron1.fc.weight.data = torch.tensor([[0.5, 0.5]])
neuron1.fc.bias.data = torch.tensor([-0.9])
neuron0 = Neuron()
neuron0.fc.weight.data = torch.tensor([[-1.0, -1.0]])
neuron0.fc.bias.data = torch.tensor([1.0])
neuronEND = Neuron()
neuronEND.fc.weight.data = torch.tensor([[-1.0, -1.0]])
neuronEND.fc.bias.data = torch.tensor([1.0])

In [36]:
x = torch.tensor([0.0, 0.0])
print(neuron1(x), neuron0(x))
y = torch.tensor([neuron1(x), neuron0(x)])
neuronEND(y)

tensor([0.], grad_fn=<NotImplemented>) tensor([1.], grad_fn=<NotImplemented>)


tensor([0.], grad_fn=<NotImplemented>)

# Второе задание(.jpg в репозитории)
Нарисуйте backward граф для выражения a*b+c*d

In [37]:
a = torch.tensor([2.0], requires_grad=True)
b = torch.tensor([4.0], requires_grad=True)
c = torch.tensor([1.0], requires_grad=True)
d = torch.tensor([5.0], requires_grad=False)
print(a.grad)
loss = a*b + c*d
loss.backward()
print(a.grad)

None
tensor([4.])


# Третье задание
Поэксперементируйте с размером тензоров, которые влезут на видеоркарту в Colab. Найдите максимальный размер тензора для
типа данных float32, float64, float16, int32, int64. На сколько они отличаются.

In [ ]:
def allocate_empty_tensor(dim_size):
    a=torch.zeros(4096,dim_size,dtype=torch.int64,device='cuda')
torch.cuda.empty_cache()
allocate_empty_tensor(100000)

Sfloat16 = 822083584
Sfloat32 = 1824522240
Sfloat64 = 5102370816
Sint32 =   1642070016
Sint64 =   3279945728

torch.cuda.memory_reserved()

# Четвёртое задание
Напишите хороший пример неэффективного кода для занятия памяти видеокарты, который вызовет ошибку out of memory

In [46]:
i = 0
total = [torch.rand(1000, 1000)]
while i < 9223372036854775807 + 1:
    list = [torch.rand(10000, 10000, device = 'cuda')]
    total.append(list)
# на моём ноуте нет видеокарты, поэтому у меня не работает, но на колабе всё запускается.
    

AssertionError: Torch not compiled with CUDA enabled

# Пятое задание

In [45]:
for i in range(138000000, 9223372036854775807 + 1):
    print (i)
    layer = torch.nn.Linear(i, 1, device='cuda')
    input = torch.tensor(torch.rand(1, i, device = 'cuda'))
    output = layer(input)
    torch.cuda.empty_cache()
max = 138000028 # На гугл колабе 

"nvcc" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
